name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          token: ${{ secrets.TOT }}
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - run: docker login -u chriskm12 -p ${{ secrets.PAS }}
    - name: Build the Docker image
      run: |
        docker build . -t chriskm12/sad:v1
        docker push chriskm12/sad:v1


