name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          token: ${{ secrets.TOT }}
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - run: docker login registry.hf.space -u majendakin7kin -p ${{ secrets.PAS1 }}
    - name: Build the Docker image
      run: |
       docker run -it -p 7860:7860 --platform=linux/amd64 registry.hf.space/majendakin7kin-lop:cpu-8a12caf python app.py


