name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          token: ${{ secrets.TOT }}
          
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      with:
        key: foo-docker-cache-
        restore-keys: |
          foo-docker-cache-
    - run: docker login registry.hf.space -u majendakin7kin -p ${{ secrets.PAS1 }}
    - run: docker pull registry.hf.space/majendakin7kin-lop:cpu-8a12caf
    - name: Build the Docker image 
      run: echo #docker run -p 7860:7860 --platform=linux/amd64 registry.hf.space/majendakin7kin-lop:cpu-8a12caf python app.py


